### ISSUE TITLE
Vulnerability. This project uses empty key pairs.

### ISSUE THREAD

**Issue by newTomas** [fisherstevenk/crystals-kyber-ts#6]
You do not generate a pair of local keys, the `_publicKey` and `_privateKey` fields remain equal to `[]`, which is why Bob and Alice have the same private and public keys. Therefore, the shared key is the same. If you add your code to generate keys, then the shared key no longer matches.

**Comment by fisherstevenk** [comment]
Hello. 

With all due respect, it does work.  It's even been reviewed by the authors of the algorithm itself. 

I'm not sure how you are using it, but the tests give you good examples on its proper usage.

**Comment by newTomas** [comment]
Explain then why the key pair is empty and generateKyberKeys is not used anywhere?

**Comment by fisherstevenk** [comment]
![image](https://github.com/fisherstevenk/crystals-kyber-ts/assets/86887231/30694c0d-1601-400c-bdb4-ad07e5942522)

**Comment by fisherstevenk** [comment]
https://github.com/fisherstevenk/crystals-kyber-ts/tree/main/tests

**Comment by newTomas** [comment]
In your implementation, only `KyberHandshake` is publicly available, which does not have a key generation method, and does not call this generation internally. What you wrote in your tests cannot be repeated without importing `KyberService`. And in the example in `readme.md`, you only mention `KyberHandshake`, as if implying that it will generate the keys itself.

**Comment by newTomas** [comment]
```typescript
import { Kyber1024Handshake } from "crystals-kyber-ts";

const bobHandshake = new Kyber1024Handshake();
const aliceHandshake = new Kyber1024Handshake();


const bobPublicKey: number[] = bobHandshake.publicKey;

//Prints 0 0 because key pair is not generated
console.log(bobPublicKey.length, bobHandshake.privateKey.length);
const aliceCipherText: number[] = aliceHandshake.generateCipherTextAndSharedSecret(bobPublicKey);

const bobSharedSecret: number[] = bobHandshake.generateRemoteSharedSecret(aliceCipherText);
```

**Comment by newTomas** [comment]
You can also assume that when you call `generateCipherTextAndSharedSecret`, a key pair will be generated, but no, you just run an empty key through `SHA3` and get the hash `a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a` which corresponds to an empty string.
kyber-handshake.ts:
![image](https://github.com/fisherstevenk/crystals-kyber-ts/assets/18233174/b091f298-b6ab-4ce2-bed4-05b96b145b5c)
kyber.service.ts:
![image](https://github.com/fisherstevenk/crystals-kyber-ts/assets/18233174/d3dd7ab7-94bd-48dd-b28a-1c2e116b4fc6)
Debugging the code from the previous comment:
![image](https://github.com/fisherstevenk/crystals-kyber-ts/assets/18233174/39e8c695-81ba-461e-9eec-91271ab0f6da)
[SHA3-256 online](https://emn178.github.io/online-tools/sha3_256.html):
![image](https://github.com/fisherstevenk/crystals-kyber-ts/assets/18233174/0240078b-0a5a-40c7-b28c-71392b79e605)

**Comment by newTomas** [comment]
```typescript
import { Kyber1024Handshake } from "crystals-kyber-ts";

const bobHandshake = new Kyber1024Handshake();
const aliceHandshake = new Kyber1024Handshake();
const chuckHandshake = new Kyber1024Handshake();


const bobPublicKey: number[] = bobHandshake.publicKey;

const aliceCipherText: number[] = aliceHandshake.generateCipherTextAndSharedSecret(bobPublicKey);

const bobSharedSecret: number[] = bobHandshake.generateRemoteSharedSecret(aliceCipherText);
const chuckSharedSecret: number[] = chuckHandshake.generateRemoteSharedSecret(aliceCipherText);
//Vulnerability! Chuck, having only the public aliceCipherText in his hands, can read all the correspondence!
console.log(Buffer.from(bobSharedSecret).equals(Buffer.from(chuckSharedSecret))); //prints true because keys is empty
```

**Comment by newTomas** [comment]
You should have the keys generated inside `KyberHandshake` automatically. It is also worth adding a key length check to `KyberService`.

**Comment by fisherstevenk** [comment]
I'm sorry.   I understand what you're saying now.

I will have an update for this soon, plus a working example repo.

Thank you.

**Comment by fisherstevenk** [comment]
v1.0.3 will automatically create the public and private keys when you create a new KyberHandshake.

https://www.npmjs.com/package/crystals-kyber-ts

**Comment by newTomas** [comment]
That's better. Thanks for the quick fix!

**Comment by fisherstevenk** [comment]
Thank you for your persistence and patience.
